# Site settings
title: Welcome !
email: souptiksen@cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Souptik Sen, Parallel Data Lab
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://souptikji.github.io" # the base hostname & protocol for your site
github_username:  souptikji
facebook_username: souptikji
linkedin_username: souptiksen

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
